<?php

namespace App\Services;

use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class TermiiService
{
    protected string $provider = 'Termii';

    protected const SUCCESS_CODE    = 'ok';
    protected const SUCCESS_MESSAGE = 'Successfully Sent';

    /**
     * Fixed OTP used in local and dev environments.
     * No SMS is sent — the code is always accepted without touching Termii.
     */
    protected const DEV_OTP = '111111';

    // ── Config ─────────────────────────────────────────────────────────────────

    protected function getApiKey(): string  { return config('services.termii.api_key'); }
    protected function getApiUrl(): string  { return config('services.termii.url'); }
    protected function getSenderId(): string { return config('services.termii.sender_id'); }
    protected function getHeaders(): array  { return ['Content-Type' => 'application/json']; }

    /**
     * Backup OTP codes — stored in config('otp.backup_codes').
     * Set via .env: OTP_BACKUP_CODES=123456,789012,... (10 codes recommended)
     *
     * Purpose: if a candidate never receives their SMS in production, an admin
     * can share one of these codes with them over a verified call/in-person.
     * Each code works regardless of phone number or purpose.
     *
     * @return array<string>
     */
    protected function getBackupCodes(): array
    {
        $raw = config('otp.backup_codes', '');
        if (empty($raw)) return [];

        return array_filter(
            array_map('trim', explode(',', $raw)),
            fn ($code) => strlen($code) > 0
        );
    }

    // ── OTP Public API ─────────────────────────────────────────────────────────

    /**
     * Generate an OTP, cache it, then send via SMS.
     * In local/dev: no SMS sent, fixed code DEV_OTP is used.
     */
    public function sendOtp(string $phone, string $purpose = 'registration'): array
    {
        if ($this->isDevEnvironment()) {
            return $this->handleDevOtp($phone, $purpose);
        }
        return $this->dispatchOtp($phone, $purpose, 'sms');
    }

    /**
     * Generate an OTP, cache it, then deliver via voice call.
     * In local/dev: no call placed, fixed code DEV_OTP is used.
     */
    public function sendOtpVoice(string $phone, string $purpose = 'registration'): array
    {
        if ($this->isDevEnvironment()) {
            return $this->handleDevOtp($phone, $purpose);
        }
        return $this->dispatchOtp($phone, $purpose, 'voice');
    }

    /**
     * Regenerate and resend OTP via the chosen channel.
     *
     * @param string $channel 'sms' | 'voice'
     */
    public function resendOtp(string $phone, string $purpose = 'registration', string $channel = 'sms'): array
    {
        Cache::forget($this->otpCacheKey($phone, $purpose));

        if ($this->isDevEnvironment()) {
            return $this->handleDevOtp($phone, $purpose);
        }

        Log::info('Termii: resending OTP', [
            'event'   => 'otp_resend',
            'phone'   => $this->maskPhone($phone),
            'purpose' => $purpose,
            'channel' => $channel,
        ]);

        return $this->dispatchOtp($phone, $purpose, $channel);
    }

    /**
     * Verify a submitted OTP.
     *
     * Verification order:
     *  1. Backup codes (any environment) — admin override path
     *  2. Dev fixed OTP '111111' (local/dev only)
     *  3. Cached OTP generated by sendOtp / resendOtp
     */
    public function verifyOtp(string $phone, string $otp, string $purpose = 'registration'): array
    {
        Log::info('Termii: OTP verification attempt', [
            'event'   => 'otp_verify_attempt',
            'phone'   => $this->maskPhone($phone),
            'purpose' => $purpose,
            'is_dev'  => $this->isDevEnvironment(),
        ]);

        // ── 1. Backup code check (all environments) ────────────────────────
        if ($this->isBackupCode($otp)) {
            Log::warning('Termii: OTP verified via backup code', [
                'event'   => 'otp_verify_backup_code',
                'phone'   => $this->maskPhone($phone),
                'purpose' => $purpose,
            ]);
            return ['success' => true, 'message' => 'OTP verified via backup code.'];
        }

        // ── 2. Dev fixed OTP (local / dev only) ───────────────────────────
        if ($this->isDevEnvironment()) {
            if ($otp === self::DEV_OTP) {
                Log::info('Termii: OTP verified via dev fixed code', [
                    'event'   => 'otp_verify_dev',
                    'phone'   => $this->maskPhone($phone),
                    'purpose' => $purpose,
                ]);
                return ['success' => true, 'message' => 'OTP verified (dev mode).'];
            }

            Log::warning('Termii: OTP incorrect in dev mode', [
                'event'    => 'otp_verify_incorrect_dev',
                'expected' => self::DEV_OTP,
            ]);
            return ['success' => false, 'message' => 'Incorrect code. In dev mode use: ' . self::DEV_OTP];
        }

        // ── 3. Cached OTP (production / staging) ──────────────────────────
        $key    = $this->otpCacheKey($phone, $purpose);
        $stored = Cache::get($key);

        if (! $stored) {
            Log::warning('Termii: OTP expired or not found', [
                'event' => 'otp_verify_expired',
                'phone' => $this->maskPhone($phone),
            ]);
            return ['success' => false, 'message' => 'OTP has expired. Please request a new one.'];
        }

        if ($stored !== $otp) {
            Log::warning('Termii: OTP incorrect', [
                'event' => 'otp_verify_incorrect',
                'phone' => $this->maskPhone($phone),
            ]);
            return ['success' => false, 'message' => 'Incorrect OTP. Please check and try again.'];
        }

        Cache::forget($key); // one-time use

        Log::info('Termii: OTP verified successfully', [
            'event'   => 'otp_verify_success',
            'phone'   => $this->maskPhone($phone),
            'purpose' => $purpose,
        ]);

        return ['success' => true, 'message' => 'OTP verified.'];
    }

    // ── General SMS ────────────────────────────────────────────────────────────

    /**
     * Send a plain SMS message (non-OTP — notifications, announcements, etc.)
     *
     * @param string|array $to  Single number or array of numbers
     */
    public function sendSms(string|array $to, string $message): array
    {
        if ($this->isDevEnvironment()) {
            Log::info('Termii: [DEV] skipping SMS send', ['to' => $to, 'message' => $message]);
            return ['success' => true, 'message' => '[Dev] SMS not sent — dev environment.'];
        }

        $numbers = is_array($to) ? $to : [$to];

        Log::info('Termii: sending SMS', ['event' => 'sms_send_attempt', 'recipients' => count($numbers)]);

        $payload = [
            'to'      => $numbers,
            'from'    => $this->getSenderId(),
            'sms'     => $message,
            'type'    => 'plain',
            'channel' => 'dnd',
            'api_key' => $this->getApiKey(),
        ];

        Log::debug('Termii: SMS payload', ['payload' => $payload]);

        try {
            $raw = Http::withHeaders($this->getHeaders())
                ->post("{$this->getApiUrl()}/api/sms/send", $payload)
                ->json();

            Log::alert('Response from ' . $this->provider, [$raw]);
            return $this->parseResult($raw);

        } catch (\Exception $e) {
            Log::error('Termii: SMS exception', ['event' => 'sms_exception', 'error' => $e->getMessage()]);
            return ['success' => false, 'message' => 'SMS service unavailable. Please try again later.'];
        }
    }

    // ── Dev Helpers ────────────────────────────────────────────────────────────

    private function isDevEnvironment(): bool
    {
        return in_array(app()->environment(), ['local', 'development', 'dev'], true);
    }

    /**
     * In dev: store DEV_OTP in cache (so the normal verify path also works)
     * and return a success response without touching Termii.
     */
    private function handleDevOtp(string $phone, string $purpose): array
    {
        Cache::put($this->otpCacheKey($phone, $purpose), self::DEV_OTP, now()->addMinutes(10));

        Log::info('Termii: [DEV] using fixed OTP, no SMS sent', [
            'event'   => 'otp_dev_fixed',
            'phone'   => $this->maskPhone($phone),
            'purpose' => $purpose,
            'otp'     => self::DEV_OTP,
        ]);

        return ['success' => true, 'message' => '[Dev] OTP is ' . self::DEV_OTP . ' — no SMS sent.'];
    }

    private function isBackupCode(string $otp): bool
    {
        $codes = $this->getBackupCodes();
        return ! empty($codes) && in_array($otp, $codes, true);
    }

    // ── Internal OTP Dispatch ─────────────────────────────────────────────────

    private function dispatchOtp(string $phone, string $purpose, string $channel): array
    {
        $otp = $this->generateOtp();
        Cache::put($this->otpCacheKey($phone, $purpose), $otp, now()->addMinutes(10));

        Log::alert('Termii: dispatching OTP', [
            'event'   => 'otp_dispatch',
            'phone'   => $this->maskPhone($phone),
            'purpose' => $purpose,
            'channel' => $channel,
            'otp' => $otp,
        ]);

        try {
            $raw = $channel === 'voice'
                ? $this->callVoiceApi($this->formatPhone($phone), $otp)
                : $this->callSmsApi($this->formatPhone($phone), $otp);

            Log::alert('Response from ' . $this->provider, [$raw]);

            $result = $this->parseResult($raw);

            if ($result['success']) {
                Log::alert('OTP sent', [
                    'event'      => 'otp_dispatch_success',
                    'phone'      => $this->maskPhone($phone),
                    'channel'    => $channel,
                    'message_id' => $raw['message_id'] ?? null,
                ]);
            } else {
                Log::error('Termii: OTP dispatch failed', [
                    'event'   => 'otp_dispatch_failed',
                    'phone'   => $this->maskPhone($phone),
                    'channel' => $channel,
                    'raw'     => $raw,
                ]);
            }

            return $result;

        } catch (\Exception $e) {
            Log::error('Termii: OTP dispatch exception', [
                'event'   => 'otp_dispatch_exception',
                'phone'   => $this->maskPhone($phone),
                'channel' => $channel,
                'error'   => $e->getMessage(),
            ]);
            return ['success' => false, 'message' => 'SMS service unavailable. Please try again later.'];
        }
    }

    // ── HTTP Calls ─────────────────────────────────────────────────────────────

    private function callSmsApi(string $phone, string $otp): array
    {
        $payload = [
            'to'      => [$phone],
            'from'    => $this->getSenderId(),
            'sms'     => "Your MG Portfolio verification code is: {$otp}. Valid for 10 minutes. Do not share.",
            'type'    => 'plain',
            'channel' => 'dnd',
            'api_key' => $this->getApiKey(),
        ];

        Log::debug('Termii: SMS payload', ['payload' => $payload]);

        return Http::withHeaders($this->getHeaders())
            ->post("{$this->getApiUrl()}/api/sms/send", $payload)
            ->json();
    }

    private function callVoiceApi(string $phone, string $otp): array
    {
        $payload = [
            'phone_number' => $phone,
            'code'         => $otp,
            'api_key'      => $this->getApiKey(),
        ];

        Log::debug('Termii: voice payload', ['phone' => $this->maskPhone($phone)]);

        return Http::withHeaders($this->getHeaders())
            ->post("{$this->getApiUrl()}/api/sms/otp/call", $payload)
            ->json();
    }

    // ── Response Parsing ───────────────────────────────────────────────────────

    private function parseResult(?array $response): array
    {
        Log::debug('Termii: parsing response', ['response' => $response]);

        if (empty($response) || ! isset($response['code'], $response['message'])) {
            Log::alert('Failed to send OTP to user', ['status' => 'unknown', 'response' => $response]);
            return ['success' => false, 'message' => 'No response from ' . $this->provider . '.', 'data' => []];
        }

        $success = $response['code'] === self::SUCCESS_CODE
            && strtolower($response['message']) === strtolower(self::SUCCESS_MESSAGE);

        $data = [
            'code'           => $response['code']           ?? null,
            'balance'        => $response['balance']        ?? null,
            'message'        => $response['message']        ?? null,
            'message_id'     => $response['message_id']     ?? null,
            'message_id_str' => $response['message_id_str'] ?? null,
        ];

        if (! $success) {
            Log::alert('Failed to send OTP to user', ['status' => $response['code'] ?? 'unknown', 'response' => $response]);
        }

        return [
            'success' => $success,
            'message' => $success ? 'Sent successfully.' : ($response['message'] ?? 'Message not sent.'),
            'data'    => $data,
        ];
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private function generateOtp(): string
    {
        return str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);
    }

    private function otpCacheKey(string $phone, string $purpose): string
    {
        return "otp:{$purpose}:" . md5($phone);
    }

    private function formatPhone(string $phone): string
    {
        $phone = preg_replace('/\D/', '', $phone);
        if (str_starts_with($phone, '0') && strlen($phone) === 11) {
            return '234' . substr($phone, 1);
        }
        if (str_starts_with($phone, '234')) return $phone;
        return '234' . $phone;
    }

    private function maskPhone(string $phone): string
    {
        return substr($phone, 0, 4) . '****' . substr($phone, -3);
    }
}
