version: '3'
services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            PHP_OPCACHE_JIT_BUFFER_SIZE: '0'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: 'client_host=host.docker.internal'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy
            redis:
                condition: service_started

    mysql:
        image: 'mysql/mysql-server:8.0'
        command: --host-cache-size=0
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'  # Allow root access from any host
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USERNAME}", "-p${DB_PASSWORD}"]
            interval: 5s
            timeout: 5s
            retries: 10

    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail

    pma:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql  # Must match the MySQL service name
            PMA_PORT: 3306
            PMA_USER: 'root'  # Using root for full access
            PMA_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: 128M
        networks:
            - sail
        depends_on:
            mysql:
                condition: service_healthy

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local